### ISSUE TITLE
[Feature Request]brew supported? 

### ISSUE THREAD

**Issue by leopku** [fangpeishi/Abbreviations#1]
Can I install Abbreviations from brew or brew cask?

**Comment by fangpsh** [comment]
Nope, the current way is easy.

## Install 

 1. Download: [Abbreviations.dictionary.zip](https://github.com/fangpeishi/Abbreviations/releases)
 2. Unzip
 3. Drag-and-drop .dictionary file into `~/Library/Dictionaries/`
 4. Restart Dictionary.app
 5. Enable Abbreviations:`Dictionary -> Preferences`
 6. Type a word

**Comment by leopku** [comment]
Thanks.
